# Generated by Django 2.2.1 on 2019-05-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionname', models.CharField(max_length=50)),
                ('num', models.BigIntegerField(max_length=11)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.VoteHeadline')),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionname', models.CharField(max_length=50)),
                ('num', models.BigIntegerField(max_length=11)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.VoteHeadline')),
            ],
        ),
    ]
