# Generated by Django 2.2.1 on 2019-05-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteheadline',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='voteoption_1',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.VoteHeadline', verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='voteoption_1',
            name='num',
            field=models.BigIntegerField(max_length=11, verbose_name='总数'),
        ),
        migrations.AlterField(
            model_name='voteoption_1',
            name='optionname',
            field=models.CharField(max_length=50, verbose_name='选项名字'),
        ),
        migrations.DeleteModel(
            name='VoteOption_2',
        ),
    ]
