# Generated by Django 2.2.1 on 2019-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190518_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteoption_1',
            name='num',
            field=models.IntegerField(default=0, verbose_name='总数'),
        ),
    ]
