# Generated by Django 2.2.1 on 2019-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20190520_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.IntegerField()),
            ],
        ),
    ]
