# Generated by Django 2.2.1 on 2019-05-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_voteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteuser',
            name='pwd',
            field=models.CharField(max_length=30),
        ),
    ]
