# Generated by Django 2.2.1 on 2019-05-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteUser',
        ),
    ]
