# Generated by Django 2.2.1 on 2019-05-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_delete_voteuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='voteheadline',
            options={'verbose_name': '标题', 'verbose_name_plural': '标题'},
        ),
        migrations.AlterModelOptions(
            name='voteoption_1',
            options={'verbose_name': '选项', 'verbose_name_plural': '选项'},
        ),
    ]
